### ISSUE TITLE
Incorrect length when using gzip

### ISSUE THREAD

**Issue by dantman** [freeall/progress-stream#10]
When enabling request's `gzip: true` I get results like this:
```js
{ percentage: 180.57896446781282,
  transferred: 272351,
  length: 150821,
  remaining: 0,
  eta: 0,
  runtime: 15,
  delta: 1530,
  speed: 16760.061538461538 }
```

The code looks something like this:
```js
request
	.get({
		url: 'https://getcomposer.org/installer',
		gzip: true,
		headers: {
			'User-Agent': 'MediaWiki-Extension-Command/' + pkg.version
		}
	})
	.pipe(progressStream({time: 100}))
	.on('progress', function(p) {
		console.log(p);
	})
	.pipe(fs.createWriteStream(installer, {
		mode: '0600',
		flags: 'wx'
	}))
	.on('error', reject)
	.on('close', function() {
		resolve(pharPath);
	});
```

And note that turning off gzip isn't even an option. This server happens to only send content-length when gzip is in use. If I turned it back off my progress would be 0 until the end.

**Comment by dantman** [comment]
Content-Length contains the length of the encoded body (correct). But request returns an inflated stream instead of the raw one and progress-stream gets the uncompressed transferred length instead of the correct compressed transferred length.

**Comment by freeall** [comment]
The way the length is read is a little complex, but you can see it here https://github.com/freeall/progress-stream/blob/master/index.js#L64-L83

I tested with your URL but it doesn't seem to send the Content-Length. Do you get the same results as me?

```
$ curl -H 'User-Agent: MediaWiki-Extension-Command/1.1.1' https://getcomposer.org/installer -i
HTTP/1.1 200 OK
Server: nginx
Date: Wed, 25 Feb 2015 09:02:29 GMT
Content-Type: text/plain
Transfer-Encoding: chunked
Connection: keep-alive
Last-Modified: Tue, 09 Dec 2014 15:40:04 GMT

#!/usr/bin/env php
....
```

**Comment by freeall** [comment]
Sorry, didn't read your comment about gzip. Forget what I just wrote.

**Comment by freeall** [comment]
You are right, when I do `curl -H 'User-Agent: MediaWiki-Extension-Command/1.1.1' --compressed https://getcomposer.org/installer -i` I get the content-length.

**Comment by freeall** [comment]
@dantman I will update it so that the length isn't set if the response headers contain `content-encoding: gzip`

**Comment by freeall** [comment]
@dantman updated to `1.0.0`. Let me know if it doesn't work for your use case.

**Comment by dantman** [comment]
It doesn't have strange side effects now. But I did want proper progress notifications with length.

I'll just try and get request core to add support for progress events internally where it's actually possible to track how much of the entity body has gone through the stream.

**Comment by freeall** [comment]
That would be great. Then I would implement that in progress-stream.
