### ISSUE TITLE
Upgrade dependencies ?

### ISSUE THREAD

**Issue by triccardi-systran** [freeall/progress-stream#15]
Would it be possible to upgrade dependencies ?
through2 now exists in major version 2, and speedometer in major version 1.

Maybe devDependencies could be updated too.

Thanks you.

**Comment by freeall** [comment]
Good idea. Do you want to do a PR with it?

**Comment by JimmyBoh** [comment]
Any update on this? Is this fixed in #18?

**Comment by ungoldman** [comment]
Opened a PR to update deps (#24) since it seems discussion on #18 has stalled.

@freeall happy to help maintain btw
